# -*- coding: utf-8 -*-
"""FactCheckingSystem(July-8).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ul-7EAKdXkg14f-N358C4tgtWeA-rf68
"""

!pip install transformers hydra_core omegaconf

from transformers import pipeline
unmasker = pipeline('fill-mask', model = 'distilbert-base-uncased')

def listToString(s): 
    
    # initialize an empty string
    str1 = " " 
    
    # return string  
    return (str1.join(s))

def findAccuracy (userInput): 

  word = userInput.split()

  length = len(word)
  articleList = ["a", "an", "the", "to", "as", "was",
                "then", "that", "which", "are", "on"]

  i = 0
  j = 0
  k = 0
  rating = 0
  newInput = ""

  counter_80 = 0
  counter_20 = 0
  weightRating_80 = 0
  weightRating_20 = 0

  for i in range(length):

    weight = 80 #in percent
    predRating = 0
    

    for j in range(len(articleList)):
      if (word[i] == articleList[j]):
        weight = 20

    
    maskList = word.copy()
    maskList[i] = "[MASK]"
    newInput = listToString(maskList)

    preds = unmasker(newInput)

    for pred in preds:

      for k in range(len(preds)):
        if (pred["score"] > predRating):
          predRating = pred["score"]

      if (pred["token_str"] == word[i]):

        if (weight == 20):
          weightRating_20 += predRating
          counter_20 += 1
        else:
          weightRating_80 += predRating
          counter_80 += 1

        print(word[i], " accurate prediction found")
        
  if (counter_20 == 0 and counter_80 == 0):
    rating = 0
  elif (counter_20 == 0 or counter_80 == 0):
    if (counter_20 == 0):
      weightRating_80 = (weightRating_80 / counter_80) * 80
      rating = (weightRating_80) / 100
    else:
      weightRating_20 = (weightRating_20 / counter_20) * 20
      rating = (weightRating_20) / 100
  else:
    weightRating_20 = (weightRating_20 / counter_20) * 20
    weightRating_80 = (weightRating_80 / counter_80) * 80

    rating = (weightRating_20 + weightRating_80) / 100  


  return rating

userInput = input("Enter your text: ")
accuracy = findAccuracy(userInput)
print("\n", accuracy, "\n", accuracy * 100, "%")

"""Output Document


Neil Armstrong was the first man on the moon : 0.405104948580265 (40.510494858026505%)

David Beckham played soccer, a sport also referred to as football. : 0.9331274231274922 (93.31274231274922%)

Neil Armstrong was the first man on the Sun. : 0.07360286017258963
(7.360286017258963%)

Barack Obama was the 44th President of the United States. : 0.624228835105896 (62.4228835105896%)

Barack Obama was the 45th President of the United States. : 0.6229093790054321 (62.290937900543206%)

Barack Obama was the president of Canada. : 0.8437768965959549 (84.37768965959549%)

Barack Obama was the prime minister of Canada. : 0.8706412633260091 (87.0641263326009%)
"""